version: '3.0'

services:
  play-dic-ct:
    image: apache/airflow:2.10.2-python3.12
    volumes:
      - ./dags:/opt/airflow/dags
    ports:
      - 8080:8080
    command: bash -c "(airflow db init && airflow users create --username admin --password admin --firstname giang --lastname nguyen --role Admin --email giangntg2301@gmail.com); airflow webserver & airflow scheduler"

volumes:
  dags:
